name: app
description: Flutter Web View Project By Natan.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  webview_flutter: ^4.0.6
  webview_flutter_android: ^3.4.2
  webview_flutter_wkwebview: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/index.html
